/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('primevue/column')['default']
    CustomerAccountInfo: typeof import('./src/components/accept/CustomerAccountInfo.vue')['default']
    CustomerAppropriateInfo: typeof import('./src/components/accept/CustomerAppropriateInfo.vue')['default']
    CustomerBasicInfo: typeof import('./src/components/accept/CustomerBasicInfo.vue')['default']
    CustomerBasicSupplement: typeof import('./src/components/accept/CustomerBasicSupplement.vue')['default']
    CustomerIdentify: typeof import('./src/components/accept/CustomerIdentify.vue')['default']
    CustomerImage: typeof import('./src/components/accept/CustomerImage.vue')['default']
    CustomerQuestionaire: typeof import('./src/components/accept/CustomerQuestionaire.vue')['default']
    CustomerRelatedInfo: typeof import('./src/components/accept/CustomerRelatedInfo.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DropdownMenu: typeof import('./src/components/DropdownMenu.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Message: typeof import('primevue/message')['default']
    NonterCustomerIdentify: typeof import('./src/components/nonCounter/NonterCustomerIdentify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
